# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170128_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
